language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
      recipients:
        - luisggm33@gmail.com
        - kennethggm12@gmail.com
      on_success: always
      on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: c76465fc-8fb8-4b95-862b-3b861c7c947e
  app: curso-ci-cd
  on:
    repo: lggm33/platzi-store-backend